# config.yaml
project_name: "Astrocyte"
samples_csv: "samples.csv"

genome: "mm10"

threads: 4

# Suffixes for new steps
filter_suffix: "_filtered"
umap_suffix: "_UMAP"
annotation_suffix: "_annotated"
MarkerGenes: markers.txt


min_tss_enrichment: 10
min_nfrags: 1000
min_gex_ngenes: 1000
max_gex_ngenes: 7000
min_gex_numi: 1500
max_gex_numi: 30000



ANNOTATIONS: annotations.txt
