# config.yaml
project_name: "Astrocyte"
samples_csv: "samples.csv"

genome: "mm10"

threads: 4

# Suffixes for new steps
filter_suffix: "_filtered"
umap_suffix: "_UMAP"
annotation_suffix: "_annotated"
MarkerGenes: markers.txt

min_tss_enrichment: 5 
min_nfrags: 1000 
min_gex_ngenes: 500 
max_gex_ngenes: 1000 
min_gex_numi: 500  
max_gex_numi: 50000 \

ANNOTATIONS: annotations.txt
